vyper-protocol/vyper-otc-ui

- api/otc-state/withdraw.ts
- idls/vyper_otc.ts
- models/OtcState.ts
> Added withdraw ix and otc state helper methods

- components/organisms/TopBar/TopBar.tsx
- pages/contract/summary/[id].tsx
- Add menu items
- Create basic routing
>  [19] Create basic nav routing

- components/molecules/SearchBar/SearchBar.module.scss
- components/molecules/SearchBar/SearchBar.tsx
- pages/contract/summary/[id].tsx
- Created SearchBar to be able to search contract by PublicKey
> Search contract by PublicKey

- api/otc-state/fecthOtcState.ts
- api/switchboard/switchboardHelper.ts
- configs/rpc_endpoints.json
- models/RateSwitchboardState.ts
- package.json
- pages/_app.tsx
- pages/contract/summary/[id].tsx
- yarn.lock
> Switchboard aggregator data

- pages/contract/summary/ClaimButton.tsx
- pages/contract/summary/DepositButton.tsx
- pages/contract/summary/SettleButton.tsx
- pages/contract/summary/WithdrawButton.tsx
- pages/contract/summary/[id].tsx
- pages/contract/summary/index.tsx
- Resolved building warnings
- Hide leftovers
> 52-Remove build warnings

- .gitignore
- .prettierrc
- package.json
- yarn.lock
> 81 - Replace local prettier config with a shared one

- src/api/otc-state/create.ts
- src/api/switchboard/switchboardHelper.ts
- src/pages/contract/create/index.tsx
- src/pages/contract/summary/[id].tsx
Fixed various eslint warnings that appeared at build time
fix #52
> 52 - Fixed Build Warnings

- src/models/OtcState.ts
> 88 - Fixed current connected wallet check

- README.md
- cypress.config.js
- netlify.toml
- package.json
- src/cypress/e2e/basic.cy.js
- yarn.lock
- Removed Cypress suite
Close #90
> 90 - Disable cypress postbuild testing

- package.json
- src/components/organisms/TopBar/TopBar.tsx
- src/components/organisms/TopBar/index.ts
- src/components/templates/ApplicationError/ApplicationError.module.scss
- src/components/templates/ApplicationError/ApplicationError.tsx
- src/components/templates/ApplicationError/index.ts
- src/components/templates/Layout/Layout.module.scss
- src/components/templates/Layout/Layout.tsx
- src/pages/_app.tsx
- yarn.lock
- Install react-error-boundary and attach `<ErrorBoundary />` in `_app.tsx`
- Create a simple error fallback component `<ApplicationError />`
Notes:
I also adjusted the `<TopBar />` component, I'm not entirely sure whether the Search bar needed to be shown on all pages also or not. So, I made a props to be able to disable the search bar and then I adjust the `<Layout />` props so that I can modify `TopBar` props from `Layout`. I think this is too complex, but I don't know whether the search bar is needed in every layout or not, if not then we should extract the search bar and add it only on the pages/components that need it
For the reference from the gif above, I modified the `src/pages/index.tsx` so I can simulate the error (without committing it), 
```js
import { useState } from …
```
> 54 - react error boundary

- src/pages/contract/summary/[id].tsx
- src/utils/numberHelpers.ts
> 100 - format floats with fixed significant digits

- src/pages/_app.tsx
> 102 - Removed wallet auto connect

- src/pages/contract/summary/[id].tsx
> 107 - formatting fix on the pnl values

- .eslintrc.json
- src/api/dummy-tokens/airdrop.ts
- src/components/molecules/AirdropButton/AirdropButton.tsx
- src/components/molecules/AirdropButton/index.ts
- src/components/organisms/TopBar/TopBar.tsx
- src/pages/contract/summary/[id].tsx
- src/utils/solanaHelper.ts
> 108 - Include airdrop button

- src/api/otc-state/fetchOtcState.ts
- src/configs/rpc_endpoints.json
- src/models/RateSwitchboardState.ts
> 111 - improved fetching performance

- .gitignore
- src/pages/_document.tsx
The change fixes the flickering problem for all the pages. It extracts the evergreen styles and adds them to the HTML of the web page
fix #78
> fix(_document.tsx): fixed Flickering UI

- package.json
- src/components/molecules/AirdropButton/AirdropButton.tsx
- src/components/organisms/ClusterSelector/ClusterSelector.tsx
- src/components/providers/TxHandlerProvider.tsx
- src/pages/_app.tsx
- src/pages/contract/create/index.tsx
- src/pages/contract/summary/[id].tsx
- yarn.lock
Improved notification for TxHandler
Close #129
Close #130
> New notification system

- .eslintrc.json
- package.json
- src/components/molecules/DateTimePickerComp/DateTimePickerComp.tsx
- src/components/molecules/DateTimePickerComp/index.ts
- src/pages/_app.tsx
- src/pages/contract/create/index.tsx
- yarn.lock
imported material ui and material ui X for date time picker component
Close #124
> New component for date time picker

- src/components/organisms/TopBar/TopBar.tsx
- src/components/providers/UrlClusterBuilderProvider.tsx
- src/pages/explorer/explorer.module.scss
- src/pages/explorer/index.tsx
> 122 - Create empty explorer route

- src/pages/index.tsx
added title Vyper OTC
fix #138
> feat(index.tsx): added title

- src/api/supabase/client.ts
- src/api/supabase/insertContract.ts
- src/api/supabase/selectContracts.ts
- src/api/switchboard/idl_switchboard_devnet.json
- src/api/switchboard/idl_switchboard_mainnet.json
- src/api/switchboard/switchboardHelper.ts
- src/api/tokens/fetchTokenInfo.ts
- src/configs/rpc_endpoints.json
- src/controllers/fetchContract/index.ts
- src/hooks/useGetFetchOTCStateQuery.ts
- src/models/plugins/RateSwitchboardState.ts
- src/models/plugins/RedeemLogicForwardState.ts
- src/pages/contract/summary/[id].tsx
- src/utils/multipleAccountHelper.ts
> 154 improved contract fetching performance

- src/api/dummy-tokens/airdrop.ts
- src/api/supabase/insertContract.ts
- src/api/switchboard/switchboardHelper.ts
- src/components/organisms/ClusterSelector/ClusterSelector.tsx
- src/components/organisms/ExplorerContractDataGrid/ExplorerContractDataGrid.tsx
- src/components/providers/TxHandlerProvider.tsx
- src/components/providers/UrlClusterBuilderProvider.tsx
- src/controllers/createContract/index.ts
- src/controllers/fetchContract/index.ts
- src/models/DbOtcState.ts
- src/models/plugins/rate/RatePythState.ts
- src/pages/contract/create/index.tsx
- src/pages/contract/summary/[id].tsx
- src/utils/clusterHelpers.ts
removed hardcoded devnet clusters
included mainnet test token support
included collateral mint selector during contract creation
fixed default cluster: mainnet
Close #162
> Mainnet Support

- src/pages/contract/summary/[id].tsx
added the size tooltip text
fix #159
> fix: added the size tooltip text

- src/api/supabase/client.ts
- src/api/supabase/notificationTrigger.ts
- src/components/providers/UrlClusterBuilderProvider.tsx
- src/controllers/createContract/index.ts
> SNS publis on contract creation

- src/controllers/createContract/OtcInitializationParams.ts
- src/controllers/createContract/index.ts
- src/controllers/fetchContract/index.ts
- src/models/plugins/rate/RatePythState.ts
- src/pages/contract/create/index.tsx
> Improve contract saving algorithm

- src/components/atoms/Icon/Icon.tsx
- src/configs/resources.json
- src/pages/index.module.scss
- src/pages/index.tsx
- src/styles/base.css
- Change home hero text
- Add telegram social link
Close #183
> 183 - Homepage improvements

- src/components/organisms/OracleLivePrice/OracleLivePrice.tsx
> 184 - fix init zero

- README.md
> 201 - new live environments

- src/components/molecules/PublicKeyLink/PublicKeyLink.tsx
- src/components/molecules/PublicKeyLink/index.ts
- src/components/organisms/ExplorerContractDataGrid/ExplorerContractDataGrid.tsx
- src/controllers/fetchContracts/index.ts
- src/models/ChainOtcState.ts
> 20 - include new columns in explorer table

- src/controllers/createContract/index.ts
- Remove leading slash in the URL
Close #210
> 210 - Remove leading slash

- src/controllers/fetchContracts/index.ts
- src/utils/multipleAccountHelper.ts
> 219 - Multiple accounts max chunk size

- src/pages/contract/create/index.tsx
- Removed mainnet test token
Close #205
> 205 - Remove mainnet test token

- netlify.toml
- package.json
- src/api/next-api/fetchTokenInfo.ts
- src/controllers/fetchContract/index.ts
- src/pages/api/token-info.ts
- yarn.lock
> 225 - Api endpoint for token info

- src/components/templates/Footer/Footer.module.scss
- src/components/templates/Layout/Layout.module.scss
- src/components/templates/Layout/Layout.tsx
- src/pages/contract/summary/[id].tsx
- src/pages/explorer/explorer.module.scss
- src/pages/explorer/index.tsx
- src/pages/index.module.scss
- src/pages/index.tsx
- Conditionally render `SearchBar` & a background cover image in `Layout`
- Apply a positive z-index to the whole main content
Close #216
> 216 - Optimize Layout component

- src/pages/contract/summary/[id].tsx
> 229 - fix hardcoded plugin type id

- src/components/organisms/ChainOtcStateDetails/ChainOtcStateDetails.module.scss
- src/components/organisms/ChainOtcStateDetails/ChainOtcStateDetails.tsx
- src/components/organisms/OracleLivePrice/OracleLivePrice.tsx
- src/hooks/useOracleLivePrice.ts
- src/models/ChainOtcState.ts
- src/pages/contract/summary/[id].tsx
> 185 - Live PnL

- src/components/templates/Footer/Footer.module.scss
- src/components/templates/Layout/Layout.module.scss
- src/components/templates/Layout/Layout.tsx
- Push the footer at the bottom of the window
Close #236
> 236 - Push the footer at the bottom of the window

- src/components/organisms/ChainOtcStateDetails/ChainOtcStateDetails.module.scss
- src/components/organisms/ChainOtcStateDetails/ChainOtcStateDetails.tsx
- src/configs/resources.json
- src/models/plugins/redeemLogic/AbsRedeemLogicPlugin.ts
- src/models/plugins/redeemLogic/RedeemLogicForwardState.ts
- Add tooltip with link to Contract Payoff Notion page
Close #241
> 241 - Add tooltip with link to Contract Payoff Notion page

- README.md
- Add folder structure tree
Close #131
> 131 - Fix readme WIP sections

- src/components/molecules/SearchBar/SearchBar.tsx
- src/components/organisms/TopBar/TopBar.module.scss
- src/components/templates/Layout/Layout.module.scss
- src/components/templates/Layout/Layout.tsx
- Fix stacking context between `Layout`, **background image** and `Topbar`
Close #247
> 247 - Unreachable wallet option buttons

- src/components/organisms/ExplorerContractDataGrid/ExplorerContractDataGrid.tsx
- src/pages/explorer/index.tsx
- Move **contract fetching logic** inside the `ExplorerContractDataGrid` component
Close #233
> 233 - Move contracts fetching in data grid

- src/pages/api/token-info.ts
added fetching token info by symbol feature in the /api/token-info endpoint
fix #231
> 231 - Added fetch token-info endpoint by token symbol

- src/components/organisms/actionButtons/DepositButton.tsx
- src/components/organisms/actionButtons/SettleButton.tsx
- src/utils/urlBuilder.ts
> 268 - QRcode shortcut

- src/api/otc-state/create.ts
- src/controllers/fetchContract/index.ts
- src/idls/redeem_logic_settled_forward.ts
- src/models/DbOtcState.ts
- src/models/plugins/redeemLogic/RedeemLogicSettledForwardPlugin.ts
> Redeem logic settled forward v0.1.1

- src/components/organisms/Simulator/Simulator.module.scss
- src/components/organisms/Simulator/Simulator.tsx
- Change fixed height of simulator
- Change note text according to `settlementPricesDescription`
_Note: I am not really sure if thats the intended behavior regarding the prices array_
Close #257
> 257 - simulator text

- package.json
- yarn.lock
> Upgrade switchboard sdk

- src/components/molecules/SearchBar/SearchBar.module.scss
- src/components/organisms/TopBar/TopBar.module.scss
- src/components/organisms/TopBar/TopBar.tsx
- made search bar responsive
- made nav menu collapsible
closes #77
> 77 - improve mobile responsiveness

- src/api/supabase/selectContracts.ts
> Filter unsupported plugins from db fetch

- src/pages/api/qr/index.ts
> Include SOL airdrop in devnet

- src/components/providers/OtcConnectionProvider.tsx
- src/configs/endpoints.json
Created a development / production rpc endpoints configuration
> New endpoints config

- src/controllers/fetchContracts/index.ts
- src/models/plugins/rate/RatePythPlugin.ts
> Improve oracle accounts decoding

- src/components/providers/OtcConnectionProvider.tsx
- src/controllers/createContract/index.ts
> Commitment during contract creation

- package.json
- yarn.lock
> 292 - bumped the switchboard sdk version

- src/models/plugins/redeemLogic/RedeemLogicVanillaOptionPlugin.ts
- src/pages/contract/create/index.tsx
> feat: hide db and notif toggles

- src/api/otc-state/create.ts
- src/idls/redeem_logic_digital.ts
- src/idls/redeem_logic_forward.ts
- src/idls/redeem_logic_settled_forward.ts
- src/idls/redeem_logic_vanilla_option.ts
Update idls for the updated redeem logics
> IDLs update

- src/components/organisms/ChainOtcStateDetails/ChainOtcStateDetails.tsx
- src/hooks/useOracleLivePrice.ts
Earlier, I was thinking of adding another react hook, but i think returning a listener remover function looks much better.
Fixes #291
> 291 - Remove Listener on contract settle

- next.config.js
- src/components/molecules/CoinBadge/CoinBadge.module.scss
- src/components/molecules/CoinBadge/CoinBadge.tsx
> Fix coinbadge component

- src/components/atoms/ButtonPill/ButtonPill.module.scss
- src/components/atoms/NumericBadge/NumericBadge.module.scss
- src/components/atoms/NumericBadge/NumericBadge.tsx
- src/components/atoms/NumericBadge/index.ts
- src/components/atoms/StatusBadge/StatusBadge.module.scss
- src/components/atoms/StatusBadge/StatusBadge.tsx
- src/components/atoms/StatusBadge/index.ts
- src/components/molecules/CoinBadge/CoinBadge.module.scss
- src/components/molecules/CoinBadge/CoinBadge.tsx
- src/components/molecules/ContractStatusBadge/ContractStatusBadge.tsx
- src/components/organisms/ChainOtcStateDetails/ChainOtcStateDetails.module.scss
- src/components/organisms/ChainOtcStateDetails/ChainOtcStateDetails.tsx
- src/components/organisms/ExplorerContractDataGrid/ExplorerContractDataGrid.tsx
- src/components/organisms/Simulator/Simulator.module.scss
- src/components/organisms/Simulator/Simulator.tsx
- src/components/organisms/TopBar/TopBar.tsx
- src/models/ChainOtcState.ts
- src/styles/base.css
> badge refactor

- src/components/atoms/ErrorAlert/ErrorAlert.tsx
- src/components/atoms/ErrorAlert/index.ts
- src/components/molecules/DateTimePickerComp/DateTimePickerComp.tsx
- src/components/molecules/ExpiryPicker/ExpiryPicker.tsx
- src/components/organisms/CreateContractFlow/CreateContractFlow.tsx
- src/utils/momentHelpers.ts
> 353 improve expiry picker

- src/components/molecules/PayoffPicker/PayoffPicker.tsx
- src/components/organisms/ChainOtcStateDetails/ChainOtcStateDetails.tsx
- src/configs/redeemLogicMetadata.json
- src/models/MetadataDetail.ts
- src/models/plugins/redeemLogic/AbsRLState.ts
- src/models/plugins/redeemLogic/digital/RLDigital.ts
- src/models/plugins/redeemLogic/forward/RLForward.ts
- src/models/plugins/redeemLogic/settledForward/RLSettledForward.ts
- src/models/plugins/redeemLogic/vanillaOption/RLVanillaOption.ts
- src/utils/redeemLogicMetadataHelper.ts
- src/utils/urlBuilder.ts
> 346 abstract payoff links and description

- src/pages/contract/create/index.tsx
> truncate oracle default price

- src/components/molecules/PreviewModal/PreviewModal.tsx
> Contract rent fee disclaimer

- src/api/supabase/readStats.ts
- src/hooks/useGetPlatformStatsQuery.ts
Created supabase utility method to fetch live stats from database.
Created react query to cache data.
Fix #366
> Read stats from database

- src/components/molecules/OraclesPicker/OraclesPicker.tsx
- src/configs/mints.json
- src/configs/oracles.json
> add oracles

- src/components/organisms/CreateContractFlow/CreateContractFlow.tsx
> fix stepper message

- src/components/organisms/Simulator/Simulator.tsx
> fix decimal digits bug

- src/utils/momentHelpers.ts
> 394 expiry picker fix

- src/api/next-api/fetchTokenInfo.ts
- src/components/molecules/ReservePicker/ReservePicker.tsx
- src/controllers/fetchContract/index.ts
- src/store/useContractStore.ts
- src/store/useTokenInfoStore.ts
> Create central local stotage for token info

- src/configs/oracles.json
> removed double oracle

- src/components/molecules/OraclesPicker/OraclesPicker.tsx
- src/components/organisms/CreateContractFlow/CreateContractFlow.tsx
- src/pages/contract/create/index.tsx
> Fixed double oracle setting

- src/components/molecules/OraclesPicker/OraclesPicker.tsx
- src/components/molecules/PreviewModal/PreviewModal.tsx
- src/components/molecules/TemplateCard/TemplateCard.tsx
> Fix template to create app error

- src/components/atoms/BooleanBadge/BooleanBadge.module.scss
- src/components/atoms/BooleanBadge/BooleanBadge.tsx
- src/components/atoms/BooleanBadge/index.ts
- src/components/atoms/ButtonPill/ButtonPill.module.scss
- src/components/atoms/ButtonPill/ButtonPill.tsx
- src/components/atoms/ClickableIcon/ClickableIcon.module.scss
- src/components/atoms/ClickableIcon/ClickableIcon.tsx
- src/components/atoms/ClickableIcon/index.ts
- src/components/atoms/LoadingValue/LoadingValue.tsx
- src/components/atoms/LoadingValue/index.ts
- src/components/atoms/StatusBadge/StatusBadge.module.scss
- src/components/atoms/TokenSymbol/TokenSymbol.module.scss
- src/components/molecules/MomentTooltipSpan/MomentTooltipSpan.tsx
- src/components/organisms/ChainOtcStateDetails/ChainOtcStateDetails.module.scss
- src/components/organisms/ChainOtcStateDetails/ChainOtcStateDetails.tsx
- src/components/organisms/Simulator/Simulator.module.scss
- src/pages/contract/summary/[id].tsx
> improve summary page

- src/api/supabase/client.ts
- src/api/supabase/syncContractData.ts
- src/controllers/fetchContract/index.ts
> Sync contract dynamic data

- src/controllers/fetchContract/index.ts
> Fixed programSellerTAAmount

- src/configs/oracles.json
> add sbf oracle

- src/api/supabase/countContracts.ts
- src/api/supabase/selectContracts.ts
- src/api/supabase/syncContractData.ts
- src/components/organisms/ExplorerContractDataGrid/ExplorerContractDataGrid.tsx
- src/controllers/fetchContracts/FetchContractsParams.ts
- src/controllers/fetchContracts/index.ts
- src/models/DbOtcDynamicData.ts
- src/models/DbOtcState.ts
- src/pages/explorer/index.tsx
> Explorer with dynamic data

- src/api/supabase/readStats.ts
> Fixed live contracts count

- src/components/molecules/OraclesPicker/OraclesPicker.tsx
- src/components/molecules/PublicKeyPicker/PublicKeyPicker.tsx
- src/components/molecules/PublicKeyPicker/index.tsx
> 345 - Create abstract publickey selector

- .gitignore
- public/robots.txt
- public/sitemap-0.xml
- public/sitemap.xml
- src/components/ChainOtcStateDetails/ChainOtcStateDetails.tsx
- src/components/CreateContractFlow/CreateContractFlow.tsx
- src/controllers/createContract/OtcInitializationParams.ts
Removed and gitignored `robots.txt` and `sitemap.xml`
Included contract creation validation
Fix #448
> Validate input params on contract creation

- src/components/ChainOtcStateDetails/ChainOtcStateDetails.tsx
- src/components/Modal/Modal.tsx
- src/components/ShareModal/ShareModal.tsx
- src/components/ShareModal/index.ts
- src/models/AbsOtcState.ts
- src/models/ChainOtcState.ts
- src/models/DbOtcState.ts
- src/utils/socialHelper.ts
in other issues we can add an image to share #314 and contextual messages based on connected wallet, e.g. pnl, direction of trade etc.
> 451 sharing contracts button

- README.md
- jest.config.js
- package.json
- src/components/AirdropButton/AirdropButton.tsx
- src/components/FeaturedProduct/FeaturedProduct.tsx
- src/components/FeaturedProduct/index.ts
- src/components/Icon/Icon.tsx
- src/components/TopBar/TopBar.module.scss
- src/components/TopBar/TopBar.tsx
- src/components/TradingViewChart/TradingViewChart.tsx
- src/components/TradingViewChart/index.ts
- src/configs/defaults.ts
- src/configs/resources.json
- src/pages/contract/create/index.tsx
- src/pages/contract/featured/sbf-to-jail/index.tsx
- src/pages/contract/featured/sol-10x/index.module.scss
- src/pages/contract/featured/sol-10x/index.tsx
- src/utils/blackScholes.test.ts
- src/utils/blackScholes.ts
- src/utils/urlBuilder.ts
- yarn.lock
> 364 refactor featured products pages

- src/components/FeaturedProduct/FeaturedProduct.tsx
- src/components/LoadingValue/LoadingValue.tsx
- src/components/TopBar/TopBar.module.scss
- src/components/TopBar/TopBar.tsx
- src/components/TradingViewChart/TradingViewChart.tsx
- src/components/TradingViewSymbol/TradingViewSymbol.tsx
- src/components/TradingViewSymbol/index.ts
- src/components/templates/Footer/Footer.module.scss
- src/pages/contract/featured/sol-10x/index.module.scss
- src/pages/contract/featured/sol-10x/index.tsx
refactor ui of featured product
> ui refactor

- src/components/BonkFixedPayout/BonkFixedPayout.module.scss
- src/components/BonkFixedPayout/BonkFixedPayout.tsx
> added more options, improved UI

- src/components/BonkFixedPayoutGiveaway/BonkFixedPayoutGiveaway.module.scss
- src/components/BonkFixedPayoutGiveaway/BonkFixedPayoutGiveaway.tsx
- src/components/BonkFixedPayoutGiveaway/index.ts
- src/pages/featured/bonk/promo/index.tsx
simplified user choice for the giveaway, move components, added link to sponsor
> 566 create promo page for tradinggiveaway

- src/api/supabase/insertContract.ts
- src/components/BonkFixedPayout/BonkFixedPayout.tsx
- src/components/BonkFixedPayoutGiveaway/BonkFixedPayoutGiveaway.tsx
- src/components/ChainOtcStateDetails/ChainOtcStateDetails.tsx
- src/components/FeaturedFixedPayout/FeaturedFixedPayout.tsx
- src/components/TemplateCard/TemplateCard.tsx
- src/configs/defaults.ts
- src/controllers/createContract/OtcInitializationParams.ts
- src/controllers/createContract/index.ts
- src/hooks/useURLReferralCode.ts
- src/models/DbOtcStateMetadata.ts
- src/pages/contract/create/index.tsx
Introduced referral system.
on supabase for referral code distribution:
```sql
select referral_code, count(*)
from contracts_metadata
group by referral_code
```
> Referral system
